/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.CTPhieuMuonBUS;
import DTO.CTPhieuMuonDTO;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import BUS.PhieuPhatBUS;
import DTO.NoiQuyPhatDTO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import BUS.NoiQuyPhatBUS;
import BUS.PhieuMuonBUS;
import DTO.PhieuMuonDTO;
import DTO.PhieuPhatDTO;
import Report.XuatDanhSachExcel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author quang
 */
public class CTPhieuMuonGUI extends javax.swing.JFrame {

    /**
     * Creates new form CTPhieuMuonGUI
     */
    private PhieuMuonDTO pm;

    public PhieuMuonDTO getPm() {
        return pm;
    }

    public void setPm(PhieuMuonDTO pm) {
        this.pm = pm;
    }

    private DefaultTableModel model;
    private DefaultTableModel modelPhat;
    public CTPhieuMuonGUI() throws Exception  {
        initComponents();
        txtMaSach.setEditable(false);
        update();
        updatePhieuPhat();
        changetxtPhat();
        changetxtMaSach();        
    }
    private CTPhieuMuonBUS bus =new CTPhieuMuonBUS();
    private NoiQuyPhatBUS busNoiQuy=new NoiQuyPhatBUS();
    private PhieuPhatBUS busPhieuPhat =new PhieuPhatBUS();
    private PhieuMuonBUS busPhieuMuon=new PhieuMuonBUS();
    private String MaPhieuMuon;
    public String getMaPhieuMuon() {
        return MaPhieuMuon;
    }

    public void setMaPhieuMuon(String MaPhieuMuon) {
        this.MaPhieuMuon = MaPhieuMuon;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtPhat = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnThemPhat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnNopPhat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JComboBox<>();
        txtTongTien = new javax.swing.JTextField();
        txtTongTien1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCTPhieuMuon = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCTPhieuPhat = new javax.swing.JTable();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Xem Chi Tiết Phiếu Mượn");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        txtPhat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhatActionPerformed(evt);
            }
        });

        jLabel2.setText("Nội dung phạt:");

        btnThemPhat.setText("Phạt");
        btnThemPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhatActionPerformed(evt);
            }
        });

        jLabel4.setText("Tổng tiền phạt:");

        btnNopPhat.setText("Nộp Phạt");
        btnNopPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNopPhatActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm Chi Tiết");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa chi tiết");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel6.setText("Mã sách:");

        jLabel7.setText("Số lượng:");

        txtMaSach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachActionPerformed(evt);
            }
        });

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTongTien.setForeground(new java.awt.Color(255, 102, 102));
        txtTongTien.setToolTipText("");
        txtTongTien.setUI(null);
        txtTongTien.setAutoscrolls(false);

        txtTongTien1.setEditable(false);
        txtTongTien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTien1ActionPerformed(evt);
            }
        });

        jButton1.setText("Xuất Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPhat, 0, 159, Short.MAX_VALUE)
                            .addComponent(txtTongTien1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTongTien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNopPhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemPhat, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnThemPhat)
                    .addComponent(txtPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNopPhat)
                    .addComponent(jLabel4)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        tableCTPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Phiếu Mượn", "Mã Sách", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(tableCTPhieuMuon);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        tableCTPhieuPhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableCTPhieuPhat);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhatActionPerformed
        // TODO add your handling code he
    }//GEN-LAST:event_txtPhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int i = tableCTPhieuMuon.getSelectedRow();
        CTPhieuMuonDTO sv =new CTPhieuMuonDTO();
        if (i>=0)
        {
            sv=bus.getInfor(i);
            int result = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                try {
                    if(bus.xoa(sv)){
                        update();
                        System.out.println("Xoa thanh cong");
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Lỗi: Còn Phiếu Phạt chưa xử lý", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(PhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
        else JOptionPane.showMessageDialog(null, "Lỗi: Bạn Chưa chọn phiểu xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachActionPerformed

    private void btnThemPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPhatActionPerformed
        // TODO add your handling code here:
        int rowIndex=tableCTPhieuMuon.getSelectedRow();
        if(rowIndex >=0){
            CTPhieuMuonDTO ctpm =new CTPhieuMuonDTO();
            ctpm=bus.getInfor(rowIndex);
            Vector row =new Vector();
            row.add(ctpm.getMaPM());
            row.add(ctpm.getMaSach());
            //lấy ma vi pham
            String[] parts;String part1;
            parts = txtPhat.getSelectedItem().toString().trim().split(" ");
            part1 = parts[0];
            row.add(part1);

            if(busNoiQuy.getList_PM()==null){
                try {
                    busNoiQuy.docDB(part1);
                } catch (Exception ex) {
                    Logger.getLogger(CTPhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            Double tien = 0.0;
            for (NoiQuyPhatDTO sv : busNoiQuy.getList_PM()){
                if(part1.equals(Integer.toString(sv.getMa()))){
                    tien=(double) (ctpm.getMaSach()*Double.parseDouble(sv.getCongThuc())*3000);
                }
            }

            row.add(tien);
            modelPhat.addRow(row);

            tableCTPhieuPhat.setModel(modelPhat);
            Double sum=0.0;
            for(int i=0;i < tableCTPhieuPhat.getRowCount();i++){
                sum+=Double.parseDouble(tableCTPhieuPhat.getValueAt(i, 3).toString());
            }


            String TongString=Double.toString(sum)+" VND";
            txtTongTien1.setText(TongString);
        }
        else JOptionPane.showMessageDialog(null, "Lỗi: Bạn Chưa chọn phiểu để phạt", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnThemPhatActionPerformed
    private void txtTongTien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTien1ActionPerformed
    }//GEN-LAST:event_txtTongTien1ActionPerformed

    private void btnNopPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNopPhatActionPerformed
        // TODO add your handling code here:
        PhieuPhatDTO sv =new PhieuPhatDTO();
        Date date = Calendar.getInstance().getTime();
        DateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
        String outputString = outputFormat.format(date);
        for (int i=0;i<tableCTPhieuPhat.getRowCount();i++){
            System.out.println(busPhieuPhat.getDefaultMaPN());
            sv.setMa(busPhieuPhat.getDefaultMaPN());
            sv.setMaPhieuMuon(Integer.parseInt(tableCTPhieuPhat.getValueAt(i, 0).toString()));
            sv.setMaSach(Integer.parseInt(tableCTPhieuPhat.getValueAt(i, 1).toString()));
            sv.setMaViPham(Integer.parseInt(tableCTPhieuPhat.getValueAt(i, 2).toString()));
            sv.setSoTienPhat(tableCTPhieuPhat.getValueAt(i, 3).toString());
            sv.setNgayViPham(outputString);
            try {
                if(busPhieuPhat.them(sv))
                   JOptionPane.showMessageDialog(null, "Nộp phạt hoàn tất", "OKE", JOptionPane.OK_OPTION);
                else JOptionPane.showMessageDialog(null, "Lỗi :Vi Phạm này đã phạt rồi", "Lỗi", JOptionPane.OK_OPTION);

            } catch (Exception ex) {
                Logger.getLogger(CTPhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnNopPhatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        CTPhieuMuonDTO sv=new CTPhieuMuonDTO();
        
        String[] parts;String part1;
        parts = txtMaSach.getSelectedItem().toString().trim().split(" ");
        part1 = parts[0];
        
        sv.setMaPM(Integer.parseInt(MaPhieuMuon));
        sv.setMaSach(Integer.parseInt(part1));
        sv.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
        
        try {
            if(bus.them(sv))
                System.out.println("Them CT thanh cong");

        } catch (Exception ex) {
            Logger.getLogger(CTPhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Lỗi :Chi tiết này đã được thêm vào rồi", "Lỗi", JOptionPane.OK_OPTION);
        }
            update();
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        XuatDanhSachExcel xuat =new XuatDanhSachExcel();
        try {
            xuat.CTPhieuMuon();
        } catch (Exception ex) {
            Logger.getLogger(CTPhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTPhieuMuonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTPhieuMuonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTPhieuMuonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTPhieuMuonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CTPhieuMuonGUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CTPhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNopPhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemPhat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableCTPhieuMuon;
    private javax.swing.JTable tableCTPhieuPhat;
    private javax.swing.JComboBox<String> txtMaSach;
    private javax.swing.JComboBox<String> txtPhat;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtTongTien1;
    // End of variables declaration//GEN-END:variables
    public void update(){
        try {
            // TODO add your handling code here:
//            if(bus.getList_PM()==null){
                if(MaPhieuMuon==null)
                    bus.docDB();
                else
                    bus.docDB(MaPhieuMuon);
            
            Vector header =new Vector();
            header.add("Mã Phiếu Mượn");
            header.add("Mã Sách");
            header.add("Số lượng");
            model = new DefaultTableModel(header,0);
            
            
            
            for (CTPhieuMuonDTO sv : bus.getList_PM()){
                Vector row =new Vector();
                row.add(sv.getMaPM());
                row.add(sv.getMaSach());
                row.add(sv.getSoLuong());
                model.addRow(row);
                
            }
            tableCTPhieuMuon.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(PhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void updatePhieuPhat(){
        try {
            // TODO add your handling code here:
            modelPhat =new DefaultTableModel();
            Vector header =new Vector();
            header.add("Mã Phiếu Mượn");
            header.add("Mã Sách");
            header.add("Lỗi");
            header.add("Tiền Nộp");
            
            modelPhat = new DefaultTableModel(header,0);
        } catch (Exception ex) {
            Logger.getLogger(PhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void changetxtPhat() throws Exception{
        // Lấy model của combobox
        DefaultComboBoxModel model = (DefaultComboBoxModel) txtPhat.getModel();

        // Xóa tất cả các phần tử hiện tại trong combobox
        model.removeAllElements();

        // Thêm các phần tử mới vào combobox
        if(busNoiQuy.getList_PM()==null){
            busNoiQuy.docDB();
        }
        for (NoiQuyPhatDTO sv : busNoiQuy.getList_PM()){
        model.addElement(sv.getMa()+" "+sv.getNoiDung());
        }

        // Cập nhật combobox với model mới
        txtPhat.setModel(model);
            
    }

    private void changetxtMaSach(){
        // Lấy model của combobox
        DefaultComboBoxModel model1 = (DefaultComboBoxModel) txtMaSach.getModel();

        // Xóa tất cả các phần tử hiện tại trong combobox
        model1.removeAllElements();

        // Thêm các phần tử mới vào combobox
        
        for (int i=0;i<10;i++){
        model1.addElement(i);
        }

        // Cập nhật combobox với model mới
        txtMaSach.setModel(model1);
    }
    private void nopPhatThanhCong(){
        try {
            if(busPhieuMuon.sua(pm)){
                System.out.println("Tra Thanh Cong");
                update();
            }
        } catch (Exception ex) {
            Logger.getLogger(PhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
