/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BUS.tacgiaBUS;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DAO.tacGiaDAO;
import DTO.tacGiaDTO;
import BUS.tacgiaBUS;
import DTO.tacGiaDTO;

/**
 *
 * @author ADMIN
 */
public class JPnAuthor extends javax.swing.JPanel {
    DefaultTableModel tableModel = new DefaultTableModel();
    ArrayList<tacGiaDTO> tgList = new ArrayList<>();

    /**
     * Creates new form JPnAuthor
     */
    public JPnAuthor() {
        initComponents();
        tableModel= (DefaultTableModel) tbltacgia.getModel();
        loadtbltacgia();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFRsearch = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRsearch = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        JFEdit = new javax.swing.JFrame();
        PnEdit = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtid1 = new javax.swing.JTextField();
        txtho1 = new javax.swing.JTextField();
        txtten1 = new javax.swing.JTextField();
        label10 = new java.awt.Label();
        Nam1 = new javax.swing.JRadioButton();
        Nu1 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        txtsdt1 = new java.awt.TextField();
        btnEdit2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JFAdd = new javax.swing.JFrame();
        PnAdd = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txtho = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        label8 = new java.awt.Label();
        Nam = new javax.swing.JRadioButton();
        Nu = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        txtsdt = new java.awt.TextField();
        btnAdd2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbltacgia = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtsearch1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboxFilter1 = new javax.swing.JComboBox();
        btnRemove = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        JFRsearch.setTitle("Tìm kiếm");
        JFRsearch.setBackground(new java.awt.Color(217, 237, 202));
        JFRsearch.setForeground(java.awt.Color.pink);
        JFRsearch.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(217, 237, 202));

        tblRsearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Họ", "Tên", "Ngày sinh", "Giới tính", "Số điện thoại"
            }
        ));
        jScrollPane2.setViewportView(tblRsearch);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JFRsearch.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 300));

        JFEdit.setTitle("Sửa độc giả");

        PnEdit.setBackground(new java.awt.Color(217, 237, 202));
        PnEdit.setPreferredSize(new java.awt.Dimension(630, 400));
        PnEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Mã nhân viên");
        PnEdit.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel16.setText("Họ");
        PnEdit.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel17.setText("Tên");
        PnEdit.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        txtid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid1ActionPerformed(evt);
            }
        });
        PnEdit.add(txtid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 240, -1));

        txtho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtho1ActionPerformed(evt);
            }
        });
        PnEdit.add(txtho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 240, -1));
        PnEdit.add(txtten1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 240, -1));

        label10.setText("Giới tính");
        PnEdit.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        buttonGroup2.add(Nam1);
        Nam1.setText("Nam");
        PnEdit.add(Nam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 69, -1));

        buttonGroup2.add(Nu1);
        Nu1.setText("Nữ");
        Nu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nu1ActionPerformed(evt);
            }
        });
        PnEdit.add(Nu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jLabel18.setText("Số điện thoại");
        PnEdit.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        txtsdt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdt1ActionPerformed(evt);
            }
        });
        PnEdit.add(txtsdt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 226, 28));

        btnEdit2.setBackground(new java.awt.Color(217, 237, 202));
        btnEdit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_edit_25px.png"))); // NOI18N
        btnEdit2.setText("Sửa");
        btnEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit2ActionPerformed(evt);
            }
        });
        PnEdit.add(btnEdit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sửa nhân viên");
        PnEdit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 610, 40));

        javax.swing.GroupLayout JFEditLayout = new javax.swing.GroupLayout(JFEdit.getContentPane());
        JFEdit.getContentPane().setLayout(JFEditLayout);
        JFEditLayout.setHorizontalGroup(
            JFEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(JFEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
        );
        JFEditLayout.setVerticalGroup(
            JFEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
            .addGroup(JFEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFEditLayout.createSequentialGroup()
                    .addComponent(PnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JFAdd.setTitle("Thêm độc giả");

        PnAdd.setBackground(new java.awt.Color(217, 237, 202));
        PnAdd.setMinimumSize(new java.awt.Dimension(611, 350));
        PnAdd.setPreferredSize(new java.awt.Dimension(630, 350));
        PnAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Mã nhân viên");
        PnAdd.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel12.setText("Họ");
        PnAdd.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        txtma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaActionPerformed(evt);
            }
        });
        PnAdd.add(txtma, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 230, -1));

        txtho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoActionPerformed(evt);
            }
        });
        PnAdd.add(txtho, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 230, -1));
        PnAdd.add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 230, -1));

        label8.setText("Giới tính");
        PnAdd.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        buttonGroup1.add(Nam);
        Nam.setText("Nam");
        PnAdd.add(Nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 69, -1));

        buttonGroup1.add(Nu);
        Nu.setText("Nữ");
        Nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuActionPerformed(evt);
            }
        });
        PnAdd.add(Nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jLabel14.setText("Số điện thoại");
        PnAdd.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        txtsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtActionPerformed(evt);
            }
        });
        PnAdd.add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 226, 28));

        btnAdd2.setBackground(new java.awt.Color(217, 237, 202));
        btnAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_25px_1.png"))); // NOI18N
        btnAdd2.setText("Thêm");
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });
        PnAdd.add(btnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thêm tác giả");
        PnAdd.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 600, 40));

        jLabel19.setText("Tên");
        PnAdd.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        javax.swing.GroupLayout JFAddLayout = new javax.swing.GroupLayout(JFAdd.getContentPane());
        JFAdd.getContentPane().setLayout(JFAddLayout);
        JFAddLayout.setHorizontalGroup(
            JFAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
            .addGroup(JFAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 602, Short.MAX_VALUE))
        );
        JFAddLayout.setVerticalGroup(
            JFAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
            .addGroup(JFAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JFAddLayout.createSequentialGroup()
                    .addComponent(PnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(217, 237, 202));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBackground(new java.awt.Color(217, 237, 202));

        tbltacgia.setBackground(new java.awt.Color(217, 237, 202));
        tbltacgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ma", "Ho", "Ten", "Gioi tinh", "So dien thoai"
            }
        ));
        tbltacgia.setToolTipText("");
        tbltacgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltacgiaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbltacgia);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 760, 420));

        jPanel4.setBackground(new java.awt.Color(217, 237, 202));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearch1ActionPerformed(evt);
            }
        });
        jPanel4.add(txtsearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tim:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        jLabel7.setText("Lọc");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 40, 30));

        cboxFilter1.setBackground(new java.awt.Color(217, 237, 202));
        cboxFilter1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mã", "Họ", "Tên" }));
        cboxFilter1.setPreferredSize(new java.awt.Dimension(12, 28));
        cboxFilter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxFilter1ActionPerformed(evt);
            }
        });
        jPanel4.add(cboxFilter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 100, -1));

        btnRemove.setBackground(new java.awt.Color(217, 237, 202));
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_remove_25px.png"))); // NOI18N
        btnRemove.setText("Xóa");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel4.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 80, 30));

        btnSearch.setBackground(new java.awt.Color(217, 237, 202));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_search_25px.png"))); // NOI18N
        btnSearch.setText("Tim");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel4.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 80, 30));

        btnEdit.setBackground(new java.awt.Color(217, 237, 202));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_edit_25px.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 80, 30));

        btnAdd.setBackground(new java.awt.Color(217, 237, 202));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_25px_1.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 90, 30));

        btnExport.setBackground(new java.awt.Color(217, 237, 202));
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_xls_25px.png"))); // NOI18N
        btnExport.setText("Xuất");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        jPanel4.add(btnExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 100, 30));

        btnImport.setBackground(new java.awt.Color(217, 237, 202));
        btnImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_xls_25px.png"))); // NOI18N
        btnImport.setText("Nhập");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        jPanel4.add(btnImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 100, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 730, 70));

        BtnUpdate.setBackground(new java.awt.Color(217, 237, 202));
        BtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_refresh_30px.png"))); // NOI18N
        BtnUpdate.setToolTipText("");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 30, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quản lý tác giả");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbltacgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltacgiaMouseClicked
        // TODO add your handling code here: DefaultTableModel md = (DefaultTableModel)tblNhanvien.getModel();
     int i = tbltacgia.getSelectedRow();
     try{
     txtid1.setText(tableModel.getValueAt(i,0).toString());
     txtho1.setText(tableModel.getValueAt(i,1).toString());
     txtten1.setText(tableModel.getValueAt(i,2).toString());
     if(buttonGroup2.equals("Nam"))
         Nam.setSelected(true);
     else Nu.setSelected(true);
     txtsdt1.setText(tableModel.getValueAt(i,4).toString());
     }catch(Exception e){System.out.println(e.toString());}
        
    }//GEN-LAST:event_tbltacgiaMouseClicked

    private void txtsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearch1ActionPerformed

    private void cboxFilter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxFilter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxFilter1ActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
       tacgiaBUS bus = new tacgiaBUS();
         int i = tbltacgia.getSelectedRow();
        if (i >= 0) {
            int Ma = Integer.parseInt(tbltacgia.getModel().getValueAt(i,0).toString());

            tgList.remove(bus.findWithId(Ma));

            bus.xoa(Ma);

            tableModel.removeRow(i);

            tbltacgia.setModel(tableModel);

            System.out.println(tgList.toString());
            JOptionPane.showMessageDialog(null, " DA XOA THANH CONG");

        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        tacgiaBUS bus = new tacgiaBUS();
        JFRsearch.setVisible(true);
        JFRsearch.setSize(630,300);
       // bus.Search(txtsearch1.getText(), cboxFilter1, jLabel8, tblRsearch);

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        JFEdit.setVisible(true);
        JFEdit.setSize(700,380);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        JFAdd.setVisible(true);
        JFAdd.setSize(700,380);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        //xuLyXuatExcel();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
    /*    int result = JOptionPane.showConfirmDialog(null,"Bạn có chắc chắn muốn nhập?");
        switch(result){
            case JOptionPane.YES_OPTION:
            xulyNhapExcel();
            break;
            case JOptionPane.NO_OPTION:
            break;
            case JOptionPane.CANCEL_OPTION:
            break;
        }*/
    }//GEN-LAST:event_btnImportActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        tacGiaDAO dataDAO = new tacGiaDAO();
        tgList = dataDAO.ReadData();
        DefaultTableModel tableModel2 =(DefaultTableModel) tbltacgia.getModel();
        System.out.println(tgList.toString());
        tableModel2.setRowCount(0);
        tgList.forEach((tg)
                -> {
            System.out.println(tg.toString());
            tableModel2.addRow(new Object[]{tg.getMa(), tg.getTen(),
                tg.getHo(), tg.getGioiTinh(),tg.getSoDienThoai()});
        }
        );
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void txtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid1ActionPerformed

    private void txtho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtho1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtho1ActionPerformed

    private void Nu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nu1ActionPerformed

    private void txtsdt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdt1ActionPerformed

    private void btnEdit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit2ActionPerformed
        // TODO add your handling code here:
         int i = tbltacgia.getSelectedRow();
        tacgiaBUS bus = new tacgiaBUS();
        if (i >= 0) {
            tacGiaDTO tg = new tacGiaDTO();

            tg.Ma = Integer.parseInt(txtma.getText());
            tg.Ten = txtten.getText();
            tg.Ho = txtho.getText();
            tg.GioiTinh= bus.getSelectedButtonText(buttonGroup1);
            tg.soDienThoai = Integer.parseInt(txtsdt.getText());
            tableModel.setValueAt(tg.Ma, i, 0);
            tableModel.setValueAt(tg.Ten, i, 1);
            
            tableModel.setValueAt(tg.Ho, i, 2);
            tableModel.setValueAt(tg.GioiTinh, i, 3);
            tableModel.setValueAt(tg.soDienThoai, i, 4);
            tbltacgia.setModel(tableModel);

            bus.sua(tg);
            JOptionPane.showMessageDialog(null, " DA SUA THANH CONG");

        
        }
    }//GEN-LAST:event_btnEdit2ActionPerformed

    private void txtmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaActionPerformed

    private void txthoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoActionPerformed

    private void NuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuActionPerformed

    private void txtsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtActionPerformed

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        // TODO add your handling code here:
       tacGiaDTO tg =  new tacGiaDTO();
       tacgiaBUS bus = new tacgiaBUS();
       tg.Ma = Integer.parseInt(txtma.getText());
        tg.Ten = txtten.getText();
        tg.Ho = txtho.getText();
        tg.GioiTinh = bus.getSelectedButtonText(buttonGroup1);
        tg.soDienThoai = Integer.parseInt(txtsdt.getText());
        
        Vector header = new Vector();
        header.add("Ma");
        header.add("Ten");
        header.add("Ho");
        header.add("GioiTinh");
        header.add("SO Dien Thoai");
        if (tableModel.getRowCount() == 0) {
            tableModel = new DefaultTableModel(header, 0);

        }
        Vector row = new Vector();

        row.add(tg.Ma);
        row.add(tg.Ten);
        row.add(tg.Ho);
        row.add(tg.GioiTinh);
        
        row.add(tg.soDienThoai);

        if (bus.checkMaTacGia(tg.getMa(),tg.getSoDienThoai())) {
            JOptionPane.showMessageDialog(null, "Mã nha xuat ban bi trung hoac so dien thoai bị trung");
        } else {
            tableModel.addRow(row);
            tbltacgia.setModel(tableModel);
            tgList.add(tg);
            bus.insert_BUS(tg);
            JOptionPane.showMessageDialog(null, "THEM tac gia THANH CONG");
            System.out.println(tgList.toString());
        }
    }//GEN-LAST:event_btnAdd2ActionPerformed
public void loadtbltacgia(){
    tacgiaBUS bus = new tacgiaBUS();
    tableModel.setRowCount(0);
       tgList = bus.getdstg();
     Vector header = new Vector();
        header.add("Mã tác giả");
        header.add("Họ");
        header.add("Tên");
        header.add("Giới tính");
        header.add("Số điện thoại");
        if(tableModel.getRowCount()==0){
            tableModel = new DefaultTableModel(header,0);
            
        }
        for (tacGiaDTO tg : tgList) {
            Vector vec = new Vector();
            vec.add(tg.getMa());
            vec.add(tg.getHo());
            vec.add(tg.getTen());
            vec.add(tg.getGioiTinh());
            vec.add(tg.getSoDienThoai());
            
            tableModel.addRow(vec);
        }
        tbltacgia.setModel(tableModel);
           
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnUpdate;
    public javax.swing.JFrame JFAdd;
    public javax.swing.JFrame JFEdit;
    public javax.swing.JFrame JFRsearch;
    public javax.swing.JRadioButton Nam;
    public javax.swing.JRadioButton Nam1;
    public javax.swing.JRadioButton Nu;
    public javax.swing.JRadioButton Nu1;
    public javax.swing.JPanel PnAdd;
    public javax.swing.JPanel PnEdit;
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnAdd2;
    public javax.swing.JButton btnEdit;
    public javax.swing.JButton btnEdit2;
    public javax.swing.JButton btnExport;
    public javax.swing.JButton btnImport;
    public javax.swing.JButton btnRemove;
    public javax.swing.JButton btnSearch;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JComboBox cboxFilter1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public java.awt.Label label10;
    public java.awt.Label label8;
    public javax.swing.JTable tblRsearch;
    public javax.swing.JTable tbltacgia;
    public javax.swing.JTextField txtho;
    public javax.swing.JTextField txtho1;
    public javax.swing.JTextField txtid1;
    public javax.swing.JTextField txtma;
    public java.awt.TextField txtsdt;
    public java.awt.TextField txtsdt1;
    public javax.swing.JTextField txtsearch1;
    public javax.swing.JTextField txtten;
    public javax.swing.JTextField txtten1;
    // End of variables declaration//GEN-END:variables
}
