/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import java.util.List;
import library.controller.*;
import library.controller.category;
import DAO.AnalyzeDAO;
import BUS.AnalyzeBUS;
import DTO.AnalyzeDTO;

/**
 *
 * @author ADMIN
 */
public class JPnAnalyze extends javax.swing.JPanel {

    /**
     * Creates new form JPnAnalyze
     */
    public JPnAnalyze() {
        AnalyzeBUS bus = new AnalyzeBUS();
        initComponents();
        jlabelSach.setText("Số lượng sách: " + bus.getsoluongSach());
        jLabelDocgia.setText("Số lượng độc giả: " + bus.getsoluongDocgia());
        jLabelMuon.setText("cho mượn: " + bus.getsoluongMuon());
        jLabelNhanvien.setText("Số lượng nhân viên: " + bus.getsoluongNhanvien());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPnAservice = new javax.swing.JPanel();
        JPnAfault = new javax.swing.JPanel();
        JPnAreader = new javax.swing.JPanel();
        JPnAstorage = new javax.swing.JPanel();
        JPnAborrow = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        intSach = new javax.swing.JPanel();
        jlabelSach = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        intDocgia = new javax.swing.JPanel();
        jLabelDocgia = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        intNhanvien = new javax.swing.JPanel();
        jLabelNhanvien = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        intNhanvien1 = new javax.swing.JPanel();
        jLabelMuon = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelservice = new javax.swing.JLabel();

        JPnAservice.setBackground(new java.awt.Color(101, 209, 51));

        javax.swing.GroupLayout JPnAserviceLayout = new javax.swing.GroupLayout(JPnAservice);
        JPnAservice.setLayout(JPnAserviceLayout);
        JPnAserviceLayout.setHorizontalGroup(
            JPnAserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        JPnAserviceLayout.setVerticalGroup(
            JPnAserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JPnAfault.setBackground(new java.awt.Color(101, 209, 51));

        javax.swing.GroupLayout JPnAfaultLayout = new javax.swing.GroupLayout(JPnAfault);
        JPnAfault.setLayout(JPnAfaultLayout);
        JPnAfaultLayout.setHorizontalGroup(
            JPnAfaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        JPnAfaultLayout.setVerticalGroup(
            JPnAfaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JPnAreader.setBackground(new java.awt.Color(101, 209, 51));

        javax.swing.GroupLayout JPnAreaderLayout = new javax.swing.GroupLayout(JPnAreader);
        JPnAreader.setLayout(JPnAreaderLayout);
        JPnAreaderLayout.setHorizontalGroup(
            JPnAreaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        JPnAreaderLayout.setVerticalGroup(
            JPnAreaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JPnAstorage.setBackground(new java.awt.Color(101, 209, 51));

        javax.swing.GroupLayout JPnAstorageLayout = new javax.swing.GroupLayout(JPnAstorage);
        JPnAstorage.setLayout(JPnAstorageLayout);
        JPnAstorageLayout.setHorizontalGroup(
            JPnAstorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        JPnAstorageLayout.setVerticalGroup(
            JPnAstorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JPnAborrow.setBackground(new java.awt.Color(101, 209, 51));

        javax.swing.GroupLayout JPnAborrowLayout = new javax.swing.GroupLayout(JPnAborrow);
        JPnAborrow.setLayout(JPnAborrowLayout);
        JPnAborrowLayout.setHorizontalGroup(
            JPnAborrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        JPnAborrowLayout.setVerticalGroup(
            JPnAborrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(217, 237, 202));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Thống kê tổng quát");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 70));

        intSach.setBackground(new java.awt.Color(101, 209, 51));
        intSach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelSach.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jlabelSach.setForeground(new java.awt.Color(255, 255, 255));
        jlabelSach.setText("Số lượng sách");
        intSach.add(jlabelSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 220, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_books_50px.png"))); // NOI18N
        intSach.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 50));

        jPanel1.add(intSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 280, 120));

        intDocgia.setBackground(new java.awt.Color(73, 175, 22));
        intDocgia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDocgia.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelDocgia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDocgia.setText("Số lượng độc giả");
        intDocgia.add(jLabelDocgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 230, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_person_50px.png"))); // NOI18N
        intDocgia.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 50));

        jPanel1.add(intDocgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 280, 120));

        intNhanvien.setBackground(new java.awt.Color(139, 202, 132));
        intNhanvien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNhanvien.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelNhanvien.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNhanvien.setText("Số lượng nhân viên");
        intNhanvien.add(jLabelNhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 230, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_worker_50px.png"))); // NOI18N
        intNhanvien.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 50));

        jPanel1.add(intNhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 280, 120));

        intNhanvien1.setBackground(new java.awt.Color(101, 209, 51));
        intNhanvien1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMuon.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelMuon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMuon.setText("cho mượn");
        intNhanvien1.add(jLabelMuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 230, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_book_50px.png"))); // NOI18N
        intNhanvien1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 50));

        jLabelservice.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelservice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelservice.setText("Số lượng sách đang");
        intNhanvien1.add(jLabelservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 230, 70));

        jPanel1.add(intNhanvien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 280, 120));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel JPnAborrow;
    public javax.swing.JPanel JPnAfault;
    public javax.swing.JPanel JPnAreader;
    public javax.swing.JPanel JPnAservice;
    public javax.swing.JPanel JPnAstorage;
    public javax.swing.JPanel intDocgia;
    public javax.swing.JPanel intNhanvien;
    public javax.swing.JPanel intNhanvien1;
    public javax.swing.JPanel intSach;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabelDocgia;
    public javax.swing.JLabel jLabelMuon;
    public javax.swing.JLabel jLabelNhanvien;
    public javax.swing.JLabel jLabelservice;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jlabelSach;
    // End of variables declaration//GEN-END:variables
}
