/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BUS.ReaderBUS;
import DAO.ReaderDAO;
import DTO.ReaderDTO;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class JPnReader extends javax.swing.JPanel {
DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
DefaultTableModel dtmDocgia = new DefaultTableModel();
ArrayList<ReaderDTO> dsdg = new ArrayList();
    /**
     * Creates new form JPnReader
     */
    public JPnReader() {
        initComponents();
        loadtblDocgia();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFAdd = new javax.swing.JFrame();
        PnAdd = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtho = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        Nam = new javax.swing.JRadioButton();
        Nu = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        txtsdt = new java.awt.TextField();
        btnAdd2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Gender = new javax.swing.ButtonGroup();
        JFEdit = new javax.swing.JFrame();
        PnEdit = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtid1 = new javax.swing.JTextField();
        txtho1 = new javax.swing.JTextField();
        txtten1 = new javax.swing.JTextField();
        dob1 = new com.toedter.calendar.JDateChooser();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        Nam1 = new javax.swing.JRadioButton();
        Nu1 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        txtsdt1 = new java.awt.TextField();
        btnEdit2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JFRsearch = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRsearch = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReader = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboxFilter = new javax.swing.JComboBox();
        btnRemove = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        JFAdd.setTitle("Thêm độc giả");

        PnAdd.setBackground(new java.awt.Color(217, 237, 202));
        PnAdd.setPreferredSize(new java.awt.Dimension(630, 300));
        PnAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Mã nhân viên");
        PnAdd.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));

        jLabel12.setText("Họ");
        PnAdd.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, -1, -1));

        jLabel13.setText("Tên");
        PnAdd.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        PnAdd.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 52, 145, -1));

        txtho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthoActionPerformed(evt);
            }
        });
        PnAdd.add(txtho, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 98, 145, -1));
        PnAdd.add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 144, 145, -1));
        PnAdd.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 52, 224, -1));

        label7.setText("Ngày sinh");
        PnAdd.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 52, -1, -1));

        label8.setText("Giới tính");
        PnAdd.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 98, -1, -1));

        Gender.add(Nam);
        Nam.setText("Nam");
        PnAdd.add(Nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 98, 69, -1));

        Gender.add(Nu);
        Nu.setText("Nữ");
        Nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuActionPerformed(evt);
            }
        });
        PnAdd.add(Nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 98, -1, -1));

        jLabel14.setText("Số điện thoại");
        PnAdd.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 150, -1, -1));

        txtsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtActionPerformed(evt);
            }
        });
        PnAdd.add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 144, 226, 28));

        btnAdd2.setBackground(new java.awt.Color(217, 237, 202));
        btnAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_25px_1.png"))); // NOI18N
        btnAdd2.setText("Thêm");
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });
        PnAdd.add(btnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thêm độc giả");
        PnAdd.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 610, 40));

        javax.swing.GroupLayout JFAddLayout = new javax.swing.GroupLayout(JFAdd.getContentPane());
        JFAdd.getContentPane().setLayout(JFAddLayout);
        JFAddLayout.setHorizontalGroup(
            JFAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(JFAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JFAddLayout.setVerticalGroup(
            JFAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(JFAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JFEdit.setTitle("Sửa độc giả");

        PnEdit.setBackground(new java.awt.Color(217, 237, 202));
        PnEdit.setPreferredSize(new java.awt.Dimension(630, 300));
        PnEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Mã nhân viên");
        PnEdit.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));

        jLabel16.setText("Họ");
        PnEdit.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, -1, -1));

        jLabel17.setText("Tên");
        PnEdit.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txtid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid1ActionPerformed(evt);
            }
        });
        PnEdit.add(txtid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 52, 145, -1));

        txtho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtho1ActionPerformed(evt);
            }
        });
        PnEdit.add(txtho1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 98, 145, -1));
        PnEdit.add(txtten1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 144, 145, -1));
        PnEdit.add(dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 52, 224, -1));

        label9.setText("Ngày sinh");
        PnEdit.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 52, -1, -1));

        label10.setText("Giới tính");
        PnEdit.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 98, -1, -1));

        Gender.add(Nam1);
        Nam1.setText("Nam");
        PnEdit.add(Nam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 98, 69, -1));

        Gender.add(Nu1);
        Nu1.setText("Nữ");
        Nu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nu1ActionPerformed(evt);
            }
        });
        PnEdit.add(Nu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 98, -1, -1));

        jLabel18.setText("Số điện thoại");
        PnEdit.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 150, -1, -1));

        txtsdt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdt1ActionPerformed(evt);
            }
        });
        PnEdit.add(txtsdt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 144, 226, 28));

        btnEdit2.setBackground(new java.awt.Color(217, 237, 202));
        btnEdit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_edit_25px.png"))); // NOI18N
        btnEdit2.setText("Sửa");
        btnEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit2ActionPerformed(evt);
            }
        });
        PnEdit.add(btnEdit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sửa độc giả");
        PnEdit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 610, 40));

        javax.swing.GroupLayout JFEditLayout = new javax.swing.GroupLayout(JFEdit.getContentPane());
        JFEdit.getContentPane().setLayout(JFEditLayout);
        JFEditLayout.setHorizontalGroup(
            JFEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(JFEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
        );
        JFEditLayout.setVerticalGroup(
            JFEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(JFEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JFRsearch.setTitle("Tìm kiếm");
        JFRsearch.setBackground(new java.awt.Color(217, 237, 202));
        JFRsearch.setForeground(java.awt.Color.pink);
        JFRsearch.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(217, 237, 202));

        tblRsearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Họ", "Tên", "Ngày sinh", "Giới tính", "Số điện thoại"
            }
        ));
        jScrollPane2.setViewportView(tblRsearch);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JFRsearch.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 300));

        setBackground(new java.awt.Color(217, 237, 202));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(217, 237, 202));

        tblReader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ma", "Ho", "Ten", "Ngay sinh", "Gioi tinh", "So dien thoai"
            }
        ));
        tblReader.setToolTipText("");
        tblReader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReaderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReader);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 730, 400));

        jPanel1.setBackground(new java.awt.Color(217, 237, 202));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 200, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tim:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        jLabel2.setText("Lọc");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 40, 30));

        cboxFilter.setBackground(new java.awt.Color(217, 237, 202));
        cboxFilter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mã", "Họ", "Tên" }));
        cboxFilter.setPreferredSize(new java.awt.Dimension(12, 28));
        cboxFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxFilterActionPerformed(evt);
            }
        });
        jPanel1.add(cboxFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 100, -1));

        btnRemove.setBackground(new java.awt.Color(217, 237, 202));
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_remove_25px.png"))); // NOI18N
        btnRemove.setText("Xóa");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 80, 30));

        btnSearch.setBackground(new java.awt.Color(217, 237, 202));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_search_25px.png"))); // NOI18N
        btnSearch.setText("Tim");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 80, 30));

        btnEdit.setBackground(new java.awt.Color(217, 237, 202));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_edit_25px.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 80, 30));

        btnAdd.setBackground(new java.awt.Color(217, 237, 202));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_25px_1.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 90, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 730, 90));

        BtnUpdate.setBackground(new java.awt.Color(217, 237, 202));
        BtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_refresh_30px.png"))); // NOI18N
        BtnUpdate.setToolTipText("");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 30, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Quản lý độc giả");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void cboxFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxFilterActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
      // TODO add your handling code here:
        dtmDocgia.setRowCount(0);
        dsdg.clear();
        Vector header = new Vector();
        header.add("Mã độc giả");
        header.add("Họ");
        header.add("Tên");
        header.add("Ngày sinh");
        header.add("Giới tính");
        header.add("Số điện thoại");
        if(dtmDocgia.getRowCount()==0)
            dtmDocgia = new DefaultTableModel(header,0);
       
        
        for(ReaderDTO dg: ReaderBUS.dsdg)
        {
            Vector row = new Vector();
            row.add(dg.id);
            row.add(dg.ho);
            row.add(dg.ten);
            row.add(dg.ngaysinh);
            row.add(dg.gioitinh);
            row.add(dg.sdt);
            dtmDocgia.addRow(row);
            dsdg.add(dg);
        }
        tblReader.setModel(dtmDocgia);
        JOptionPane.showMessageDialog(null,"Update Succesfully.");
        
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txthoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoActionPerformed

    private void NuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuActionPerformed

    private void txtsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtActionPerformed

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        // TODO add your handling code here:
        ReaderBUS bus = new ReaderBUS();
        ReaderDTO rd = new ReaderDTO();
        rd.id=txtid.getText();
        rd.ho=txtho.getText();
        rd.ten=txtten.getText();
        rd.ngaysinh=dateFormat.format(dob.getDate());
        rd.gioitinh=bus.getSelectedButtonText(Gender);
        rd.sdt=txtsdt.getText();
     //   bus.khoitao(rd, dtmDocgia, tblReader);
        Vector header = new Vector();
        header.add("Mã độc giả");
        header.add("Họ độc giả");
        header.add("Tên độc giả");
        header.add("Ngày sinh");
        header.add("Giới tính");
        header.add("Số điện thoại");
   if(dtmDocgia.getRowCount()==0){
       dtmDocgia = new DefaultTableModel(header,0);
   }
   bus.khoitao(rd,dtmDocgia,tblReader);
 
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
                JFAdd.setVisible(true);
        JFAdd.setSize(630,300);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        ReaderBUS bus = new ReaderBUS();
        
        int i = tblReader.getSelectedRow();
        if(i>=0){
            String ma = tblReader.getModel().getValueAt(i,0).toString();
            dsdg.remove(bus.timkiemtheoMa(ma));
            bus.xoa(ma);
            dtmDocgia.removeRow(i);
            tblReader.setModel(dtmDocgia);
            JOptionPane.showMessageDialog(null,"Delete Successfully.");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid1ActionPerformed

    private void txtho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtho1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtho1ActionPerformed

    private void Nu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nu1ActionPerformed

    private void txtsdt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdt1ActionPerformed

    private void btnEdit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit2ActionPerformed
        // TODO add your handling code here:
        int i = tblReader.getSelectedRow();
        ReaderBUS bus = new ReaderBUS();
        if(i>=0){
            ReaderDTO rd = new ReaderDTO();
        rd.id = txtid1.getText();
        rd.ho = txtho1.getText();
        rd.ten = txtten1.getText();
        rd.ngaysinh = dateFormat.format(dob1.getDate());
        rd.gioitinh = bus.getSelectedButtonText(Gender);
        rd.sdt = txtsdt1.getText();
        
            dtmDocgia.setValueAt(rd.id,i,0);
            dtmDocgia.setValueAt(rd.ho,i,1);
            dtmDocgia.setValueAt(rd.ten,i,2);
            dtmDocgia.setValueAt(rd.ngaysinh,i,3);
            dtmDocgia.setValueAt(rd.gioitinh, i, 4);
            dtmDocgia.setValueAt(rd.sdt,i,5);
            tblReader.setModel(dtmDocgia);
        bus.sua(rd);
            JOptionPane.showMessageDialog(null,"Edit Successfully.");
        }
    }//GEN-LAST:event_btnEdit2ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        JFEdit.setVisible(true);
        JFEdit.setSize(630,300);
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblReaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReaderMouseClicked
        // TODO add your handling code here:
         DefaultTableModel md = (DefaultTableModel)tblReader.getModel();
     int i = tblReader.getSelectedRow();
     try{
     txtid1.setText(md.getValueAt(i,0).toString());
     txtho1.setText(md.getValueAt(i,1).toString());
     txtten1.setText(md.getValueAt(i,2).toString());
     Date date;
        date = dateFormat.parse((String)md.getValueAt(i,3).toString());
     dob1.setDate(date);
        ;
     String gt = md.getValueAt(i,4).toString();
     if(Gender.equals("Nam"))
         Nam.setSelected(true);
     else Nu.setSelected(true);
     txtsdt1.setText(md.getValueAt(i,5).toString());
     }catch(Exception e){System.out.println(e.toString());}
    }//GEN-LAST:event_tblReaderMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        ReaderBUS bus = new ReaderBUS();
        JFRsearch.setVisible(true);
        JFRsearch.setSize(630,300);
        bus.Search(txtsearch.getText(), cboxFilter, jLabel3, tblRsearch);
        
    }//GEN-LAST:event_btnSearchActionPerformed
public void loadtblDocgia(){
     dtmDocgia.setRowCount(0);
       dsdg = ReaderBUS.getdsdg();
     Vector header = new Vector();
        header.add("Mã nhân viên");
        header.add("Họ");
        header.add("Tên");
        header.add("Ngày sinh");
        header.add("Giới tính");
        header.add("Số điện thoại");
        if(dtmDocgia.getRowCount()==0){
            dtmDocgia = new DefaultTableModel(header,0);
            
        }
        for (ReaderDTO dg : dsdg) {
            Vector vec = new Vector();
            vec.add(dg.getid());
            vec.add(dg.getho());
            vec.add(dg.getten());
            vec.add(dg.getngaysinh());
            vec.add(dg.getgioitinh());
            vec.add(dg.getsdt());
            
            dtmDocgia.addRow(vec);
        }
        tblReader.setModel(dtmDocgia);
           

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnUpdate;
    public javax.swing.ButtonGroup Gender;
    public javax.swing.JFrame JFAdd;
    public javax.swing.JFrame JFEdit;
    public javax.swing.JFrame JFRsearch;
    public javax.swing.JRadioButton Nam;
    public javax.swing.JRadioButton Nam1;
    public javax.swing.JRadioButton Nu;
    public javax.swing.JRadioButton Nu1;
    public javax.swing.JPanel PnAdd;
    public javax.swing.JPanel PnEdit;
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnAdd2;
    public javax.swing.JButton btnEdit;
    public javax.swing.JButton btnEdit2;
    public javax.swing.JButton btnRemove;
    public javax.swing.JButton btnSearch;
    public javax.swing.JComboBox cboxFilter;
    public com.toedter.calendar.JDateChooser dob;
    public com.toedter.calendar.JDateChooser dob1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public java.awt.Label label10;
    public java.awt.Label label7;
    public java.awt.Label label8;
    public java.awt.Label label9;
    public javax.swing.JTable tblReader;
    public javax.swing.JTable tblRsearch;
    public javax.swing.JTextField txtho;
    public javax.swing.JTextField txtho1;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtid1;
    public java.awt.TextField txtsdt;
    public java.awt.TextField txtsdt1;
    public javax.swing.JTextField txtsearch;
    public javax.swing.JTextField txtten;
    public javax.swing.JTextField txtten1;
    // End of variables declaration//GEN-END:variables
}
