/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import DTO.ReaderDTO;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashSet;
import library.controller.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import library.Forms.Transition;
/**
 *
 * @author ADMIN
 */
public class Menu extends javax.swing.JFrame {
        List<ReaderDTO> dsdg = new ArrayList();
        DefaultTableModel model = new DefaultTableModel();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Connection con = null;
        
        
            
        
    /**
     * Creates new form Menu
     */
    public Menu() {
        ArrayList<Image> icons = new ArrayList();
        setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\ADMIN\\Desktop\\Java\\Library\\src\\image\\icons8_library_100px.png"));
        setTitle("Quan ly thu vien");
        initComponents();
        Controller controller = new Controller(JPnContent);
        controller.setView(JPnStorage);
        List<category> cate = new ArrayList();
         cate.add(new category("Search",JPnSearch));
         cate.add(new category("Books",JPnBooks));
         cate.add(new category("Reader",JPnReader));
         cate.add(new category("Service",JPnService));
         cate.add(new category("Employee",JPnEmployee));
         cate.add(new category("Storage",JPnStorage));
         cate.add(new category("Default",JPnHome));
         cate.add(new category("Analyze",JPnAnalyze));
         cate.add(new category("Author",JPnAuthor));
         cate.add(new category("NXB",JPnNXB));
         controller.setEvent(cate);
        
         

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPnStat = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Sidebar = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        JPnSearch = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LblSearch = new javax.swing.JLabel();
        JPnBooks = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LblBooks = new javax.swing.JLabel();
        JPnReader = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LblReader = new javax.swing.JLabel();
        JPnHome = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        JPnAuthor = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        LblAuthor = new javax.swing.JLabel();
        JPnEmployee = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        LblEmployee = new javax.swing.JLabel();
        JPnService = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LblService = new javax.swing.JLabel();
        JPnStorage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LblStorage = new javax.swing.JLabel();
        JPnNXB = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        LblAnalyze1 = new javax.swing.JLabel();
        JPnAnalyze = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        LblAnalyze = new javax.swing.JLabel();
        JPnContent = new javax.swing.JPanel();

        JPnStat.setBackground(new java.awt.Color(43, 152, 54));
        JPnStat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(73, 175, 22));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Số lượng đang mượn");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        JPnStat.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 210, 112));

        jPanel4.setBackground(new java.awt.Color(139, 202, 132));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 112));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Số lượng độc giả");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 6, 200, -1));

        jLabel10.setText("jLabel10");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        JPnStat.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        jPanel5.setBackground(new java.awt.Color(101, 209, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Số lượng sách");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 6, 230, -1));

        JPnStat.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 230, 112));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(43, 152, 64));

        Sidebar.setBackground(new java.awt.Color(43, 152, 64));
        Sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Sidebar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 10));

        JPnSearch.setBackground(new java.awt.Color(43, 152, 54));
        JPnSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_search_50px.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        JPnSearch.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        LblSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblSearch.setForeground(new java.awt.Color(255, 255, 255));
        LblSearch.setText("Tìm kiếm");
        JPnSearch.add(LblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 95, -1));

        Sidebar.add(JPnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, -1));

        JPnBooks.setBackground(new java.awt.Color(43, 152, 64));
        JPnBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_book_50px.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        JPnBooks.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        LblBooks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblBooks.setForeground(new java.awt.Color(255, 255, 255));
        LblBooks.setText("Sách");
        JPnBooks.add(LblBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 95, -1));

        Sidebar.add(JPnBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, -1));

        JPnReader.setBackground(new java.awt.Color(43, 152, 64));
        JPnReader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPnReaderMousePressed(evt);
            }
        });
        JPnReader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_person_50px.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        JPnReader.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        LblReader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblReader.setForeground(new java.awt.Color(255, 255, 255));
        LblReader.setText("Độc giả");
        JPnReader.add(LblReader, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 95, -1));

        Sidebar.add(JPnReader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, -1));

        JPnHome.setBackground(new java.awt.Color(43, 152, 54));
        JPnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_library_100px.png"))); // NOI18N
        JPnHome.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 290, -1));

        Sidebar.add(JPnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 110));

        JPnAuthor.setBackground(new java.awt.Color(43, 152, 64));
        JPnAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnAuthorMouseClicked(evt);
            }
        });
        JPnAuthor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_user_typing_using_typewriter_50px.png"))); // NOI18N
        jLabel11.setText("jLabel1");
        JPnAuthor.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        LblAuthor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblAuthor.setForeground(new java.awt.Color(255, 255, 255));
        LblAuthor.setText("Tác giả");
        JPnAuthor.add(LblAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, -1));

        Sidebar.add(JPnAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 300, -1));

        JPnEmployee.setBackground(new java.awt.Color(43, 152, 64));
        JPnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPnEmployeeMousePressed(evt);
            }
        });
        JPnEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_worker_50px.png"))); // NOI18N
        jLabel12.setText("jLabel1");
        JPnEmployee.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 50));

        LblEmployee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblEmployee.setForeground(new java.awt.Color(255, 255, 255));
        LblEmployee.setText("Nhân viên");
        JPnEmployee.add(LblEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 95, -1));

        Sidebar.add(JPnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 300, -1));

        JPnService.setBackground(new java.awt.Color(43, 152, 64));
        JPnService.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_books_50px.png"))); // NOI18N
        jLabel5.setText("jLabel1");
        JPnService.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        LblService.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblService.setForeground(new java.awt.Color(255, 255, 255));
        LblService.setText("Mượn / trả");
        JPnService.add(LblService, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 150, -1));

        Sidebar.add(JPnService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 300, -1));

        JPnStorage.setBackground(new java.awt.Color(43, 152, 64));
        JPnStorage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_homework_50px.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        JPnStorage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        LblStorage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblStorage.setForeground(new java.awt.Color(255, 255, 255));
        LblStorage.setText("Kho");
        JPnStorage.add(LblStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 150, -1));

        Sidebar.add(JPnStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 300, -1));

        JPnNXB.setBackground(new java.awt.Color(43, 152, 64));
        JPnNXB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_supplier_50px_1.png"))); // NOI18N
        jLabel13.setText("jLabel1");
        JPnNXB.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        LblAnalyze1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblAnalyze1.setForeground(new java.awt.Color(255, 255, 255));
        LblAnalyze1.setText("Nhà xuất bản");
        JPnNXB.add(LblAnalyze1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 150, -1));

        Sidebar.add(JPnNXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 300, -1));

        JPnAnalyze.setBackground(new java.awt.Color(43, 152, 64));
        JPnAnalyze.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_analyze_50px_2.png"))); // NOI18N
        jLabel9.setText("jLabel1");
        JPnAnalyze.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        LblAnalyze.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblAnalyze.setForeground(new java.awt.Color(255, 255, 255));
        LblAnalyze.setText("Thống kê");
        JPnAnalyze.add(LblAnalyze, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 15, 150, -1));

        Sidebar.add(JPnAnalyze, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 300, -1));

        javax.swing.GroupLayout JPnContentLayout = new javax.swing.GroupLayout(JPnContent);
        JPnContent.setLayout(JPnContentLayout);
        JPnContentLayout.setHorizontalGroup(
            JPnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        JPnContentLayout.setVerticalGroup(
            JPnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPnContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPnReaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnReaderMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPnReaderMousePressed

    private void JPnEmployeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnEmployeeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPnEmployeeMousePressed

    private void JPnAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnAuthorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JPnAuthorMouseClicked

    
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(0,51,51));
    }
    void setColor(Panel panel){
        panel.setBackground(new Color(0,51,51));
    }
    
    void ResetColor(Panel panel){
        panel.setBackground(new Color(0,0,0));
    }
    void ResetColor(JPanel panel){
        panel.setBackground(new Color(0,0,0));
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPnAnalyze;
    private javax.swing.JPanel JPnAuthor;
    private javax.swing.JPanel JPnBooks;
    private javax.swing.JPanel JPnContent;
    private javax.swing.JPanel JPnEmployee;
    private javax.swing.JPanel JPnHome;
    private javax.swing.JPanel JPnNXB;
    private javax.swing.JPanel JPnReader;
    private javax.swing.JPanel JPnSearch;
    private javax.swing.JPanel JPnService;
    private javax.swing.JPanel JPnStat;
    private javax.swing.JPanel JPnStorage;
    private javax.swing.JLabel LblAnalyze;
    private javax.swing.JLabel LblAnalyze1;
    private javax.swing.JLabel LblAuthor;
    private javax.swing.JLabel LblBooks;
    private javax.swing.JLabel LblEmployee;
    private javax.swing.JLabel LblReader;
    private javax.swing.JLabel LblSearch;
    private javax.swing.JLabel LblService;
    private javax.swing.JLabel LblStorage;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
