/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.NhanVienBUS;
import DTO.NhanVienDTO;
import com.toedter.calendar.JDateChooser;
import java.text.ParseException;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import BUS.PhieuMuonBUS;
import DTO.PhieuMuonDTO;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;


/**
 *
 * @author quang
 */
public class PhieuMuon extends javax.swing.JFrame {

    /**
     * Creates new form PhieuMuonGUI
     */
    private DefaultTableModel model;
    public PhieuMuon()  throws Exception {
        initComponents();
        update();
        changejcombobox1();
        changejcombobox2();
        setDefaultDateNgayTra(txtNgayTra);  
    }
    private PhieuMuonBUS bus=new PhieuMuonBUS();
    private NhanVienBUS busNhanVien =new NhanVienBUS();            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhieuMuon = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btncapnhat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNgayMuon = new com.toedter.calendar.JDateChooser();
        txtNgayTra = new com.toedter.calendar.JDateChooser();
        btnLuu = new javax.swing.JButton();
        btnTra = new javax.swing.JButton();
        btnXem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách phiếu mượn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tablePhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên Nhân Viên", "Tên Đọc Giả", "Ngày Mượn", "Ngày Trả", "Ngày Trả Thực", "Trạng Thái"
            }
        ));
        tablePhieuMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePhieuMuonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePhieuMuon);
        if (tablePhieuMuon.getColumnModel().getColumnCount() > 0) {
            tablePhieuMuon.getColumnModel().getColumn(0).setPreferredWidth(40);
            tablePhieuMuon.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jLabel2.setText("Tên Nhân Viên:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Tên Đọc Giả:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThem.setBackground(new java.awt.Color(153, 255, 153));
        btnThem.setText("Thêm Phiếu");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 102, 102));
        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btncapnhat.setBackground(new java.awt.Color(204, 204, 255));
        btncapnhat.setText("Làm Mới");
        btncapnhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncapnhatMouseClicked(evt);
            }
        });
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        jLabel6.setText("Ngày Mượn:");

        jLabel7.setText("Ngày Trả:");

        txtNgayMuon.setToolTipText("");
        txtNgayMuon.setAutoscrolls(true);
        txtNgayMuon.setDate(Calendar.getInstance().getTime());
        txtNgayMuon.setEnabled(false);
        txtNgayMuon.setFocusCycleRoot(true);
        txtNgayMuon.setFocusTraversalPolicy(null);

        btnLuu.setBackground(new java.awt.Color(51, 204, 255));
        btnLuu.setText("Lưu");
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnTra.setBackground(new java.awt.Color(204, 204, 204));
        btnTra.setText("Trả Sách");
        btnTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTraMouseClicked(evt);
            }
        });
        btnTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraActionPerformed(evt);
            }
        });

        btnXem.setBackground(new java.awt.Color(255, 181, 224));
        btnXem.setText("Xem Chi Tiết");
        btnXem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXemMouseClicked(evt);
            }
        });
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });

        jButton1.setText("Xem Chi Tiết Tất Cả");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNgayTra, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btncapnhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLuu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTra, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        //gồm 2 phần: thêm phiếu mượn mới vào db và mở chi tiết phiếu để nhập 
        PhieuMuonDTO sv =new PhieuMuonDTO();
        
        String[] parts;String part1,part2;
        parts = jComboBox2.getSelectedItem().toString().trim().split(" ");
        part1 = parts[0];
        
        parts = jComboBox1.getSelectedItem().toString().trim().split(" ");
        part2 = parts[0];
        
        Date ngayMuon = txtNgayMuon.getDate();
        Date ngayTra =txtNgayTra.getDate();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        // Chuyển đổi sang kiểu Date
        String strDateMuon = dateFormat.format(ngayMuon);
        String strDateTra = dateFormat.format(ngayTra);
        
        sv.setMa(bus.getDefaultMaPN());
        sv.setMaDG(Integer.parseInt(part1));
        sv.setMaNV(Integer.parseInt(part2));
        sv.setNgayMuon(strDateMuon);
        sv.setNgayTra(strDateTra);
        sv.setTrangThai(0);

        try {
            if(bus.them(sv)){
                System.out.println("Them thanh cong");
                update();}
        } catch (Exception ex) {
            Logger.getLogger(PhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
//      Mở chi tiết phiếu vừa tạo
        mochitiet(Integer.toString(sv.getMa()));

    }                                       

    private void btncapnhatMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        update();
    }                                       

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        int rowIndex = tablePhieuMuon.getSelectedRow();
        if(rowIndex>=0){
            PhieuMuonDTO sv = new PhieuMuonDTO();
            
            String[] parts;String part1,part2;
            parts = jComboBox2.getSelectedItem().toString().trim().split(" ");
            part1 = parts[0];

            parts = jComboBox1.getSelectedItem().toString().trim().split(" ");
            part2 = parts[0];

            Date ngayMuon = txtNgayMuon.getDate();
            Date ngayTra =txtNgayTra.getDate();
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            // Chuyển đổi sang kiểu Date
            String strDateMuon = dateFormat.format(ngayMuon);
            String strDateTra = dateFormat.format(ngayTra);

            String value = tablePhieuMuon.getValueAt(rowIndex, 0).toString();
            String value1 ;
            //trừ trường hợp chưa trả
            if(tablePhieuMuon.getValueAt(rowIndex, 5)==null)
            value1=null;
            else
            value1= tablePhieuMuon.getValueAt(rowIndex, 5).toString();
            
            sv.setMa(Integer.parseInt((String) value));
            sv.setMaDG(Integer.parseInt(part1));
            sv.setMaNV(Integer.parseInt(part2));
            sv.setNgayMuon(strDateMuon);
            sv.setNgayTraThuc((String) value1);
            sv.setNgayTra(strDateTra);
            sv.setTrangThai(0);
            try {
                if(bus.sua(sv)){
                    System.out.println("Sua Thanh cong");
                    update();
                }
            } catch (Exception ex) {
                Logger.getLogger(PhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else JOptionPane.showMessageDialog(null, "Lỗi: Bạn Chưa chọn phiểu để Lưu", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }                                   

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        int i = tablePhieuMuon.getSelectedRow();
        PhieuMuonDTO sv =new PhieuMuonDTO();
        sv=bus.getInfor(i);
        if (i>=0)
        {
            int result = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                try {
                    if(bus.xoa(sv)){
                        update();
                        System.out.println("Xoa thanh cong");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(PhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
        else JOptionPane.showMessageDialog(null, "Lỗi: Bạn Chưa chọn phiểu xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        
    }                                   

    private void btnTraMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        int rowIndex=tablePhieuMuon.getSelectedRow();
        if(rowIndex>=0){
            String value = (String) tablePhieuMuon.getValueAt(rowIndex, 5);
            if(value==null){
                PhieuMuonDTO sv =new PhieuMuonDTO();
                sv=bus.getInfor(rowIndex);
                Date date = Calendar.getInstance().getTime();
                DateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
                String outputString = outputFormat.format(date);
                sv.setNgayTraThuc(outputString);
                sv.setTrangThai(1);
                
                
                //xét điều kiện ngày trả thữ trễ hơn dự tính
                String date1 =sv.getNgayTra();
                String date2 =outputString;

                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date d1 = null;
                Date d2 = null;
                try {
                    d1 = dateFormat.parse(date1);
                    d2 = dateFormat.parse(date2);
                } catch (ParseException ex) {
                    Logger.getLogger(PhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                //xet thoi gian tra cos tre han khong
                long diff = d2.getTime() - d1.getTime();
                
                if (diff <= 0) {
                    mochitiet(Integer.toString(sv.getMa()));
                    
                } else {
                    mochitiet(Integer.toString(sv.getMa()));
                }
            }
            else
                JOptionPane.showMessageDialog(null, "Lỗi: Đã được trả rồi", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(null, "Lỗi: Bạn Chưa chọn phiểu để trả", "Lỗi", JOptionPane.ERROR_MESSAGE);
    }                                   

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        int i=tablePhieuMuon.getSelectedRow();
        PhieuMuonDTO sv= new PhieuMuonDTO();
        sv=bus.getInfor(i);
        mochitiet(Integer.toString(sv.getMa()));
    }                                      

    private void btnXemMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        
    }                                   

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btnTraActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        mochitiet();
    }                                        

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void tablePhieuMuonMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        int rowIndex = tablePhieuMuon.getSelectedRow();
        if(rowIndex>=0){
            
            //Xuất ra jcombobox1
            String value = tablePhieuMuon.getValueAt(rowIndex, 1).toString();
            if (value != null) {
                for (int i = 0; i < jComboBox1.getItemCount(); i++) {
                String item = (String) jComboBox1.getItemAt(i);
                    if (value.equals(item)) {
                        jComboBox1.setSelectedItem(item);
                        break;
                    }
                }
            }
            //Xuất ra jcombobox2
            value = tablePhieuMuon.getValueAt(rowIndex, 2).toString();
            if (value != null) {
                for (int i = 0; i < jComboBox2.getItemCount(); i++) {
                String item = (String) jComboBox2.getItemAt(i);
                    if (value.equals(item)) {
                        jComboBox2.setSelectedItem(item);
                        break;
                    }
                }
            }
            // Xuất ra txtNgayMuon
            // Lấy giá trị của cột 2 trong dòng được chọn
            String dateString = tablePhieuMuon.getModel().getValueAt(rowIndex, 3).toString();

            // Chuyển đổi giá trị của cột 2 sang kiểu Date
            try {
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateString);
                // Đưa giá trị Date vào JDateChooser
                txtNgayMuon.setDate(date);
            } catch (ParseException e) {
                e.printStackTrace();
            }
            
//            Xuất dữu liệu ra txtNgayTra
            // Lấy giá trị của cột 2 trong dòng được chọn
            dateString = tablePhieuMuon.getModel().getValueAt(rowIndex, 4).toString();

            // Chuyển đổi giá trị của cột 2 sang kiểu Date
            try {
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateString);
                // Đưa giá trị Date vào JDateChooser
                txtNgayTra.setDate(date);
            } catch (ParseException e) {
                e.printStackTrace();
            }
        }
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuMuonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuMuonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuMuonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuMuonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PhieuMuonGUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(PhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTra;
    private javax.swing.JButton btnXem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePhieuMuon;
    private com.toedter.calendar.JDateChooser txtNgayMuon;
    private com.toedter.calendar.JDateChooser txtNgayTra;
    // End of variables declaration                   
    private void changejcombobox2(){
        // Lấy model của combobox
            DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox2.getModel();

            // Xóa tất cả các phần tử hiện tại trong combobox
            model.removeAllElements();

            // Thêm các phần tử mới vào combobox
            model.addElement("1");
            model.addElement("2");
            model.addElement("3");

            // Cập nhật combobox với model mới
            jComboBox2.setModel(model);
    }
    private void changejcombobox1() throws Exception{
        // Lấy model của combobox
            DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox1.getModel();

            // Xóa tất cả các phần tử hiện tại trong combobox
            model.removeAllElements();

            // Thêm các phần tử mới vào combobox
            if(busNhanVien.getList_PM()==null){
                busNhanVien.docDB();
            }
            for (NhanVienDTO sv : busNhanVien.getList_PM()){
            model.addElement(sv.getMa()+" "+sv.getHo()+" "+sv.getTen());
            }

            // Cập nhật combobox với model mới
            jComboBox1.setModel(model);
            
    }
    private void update(){
        try {
            // TODO add your handling code here:
            if(bus.getList_PM()==null){
                bus.docDB();
            }
            Vector header =new Vector();
            header.add("Mã");
            header.add("Mã nhân viên");
            header.add("Mã đọc giả");
            header.add("Ngày mượn");
            header.add("Ngày trả");
            header.add("Ngày trả thực");
            header.add("Trạng thái");
            model = new DefaultTableModel(header,0);
            
            //thử hashmap
            HashMap<Integer, String> mapNhanVien = new HashMap<>();
            if(busNhanVien.getList_PM()==null){
                    busNhanVien.docDB();
            }
            for (NhanVienDTO sv : busNhanVien.getList_PM()){
                mapNhanVien.put(sv.getMa(), sv.getHo()+' '+sv.getTen());            
            }
            //
            
            for (PhieuMuonDTO sv : bus.getList_PM()){
                Vector row =new Vector();
                row.add(sv.getMa());
                
                // Lặp qua tất cả các key trong Map và lấy giá trị tương ứng
                for (int key : mapNhanVien.keySet()) {
                    String value = mapNhanVien.get(key);
                    if(sv.getMaNV()==key)
                        row.add(sv.getMaNV()+" "+value);
                }
                
                
                row.add(sv.getMaDG());
                row.add(sv.getNgayMuon());
                row.add(sv.getNgayTra());
                row.add(sv.getNgayTraThuc());
                row.add(sv.getTrangThai());
                model.addRow(row);
                
            }
            tablePhieuMuon.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(PhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setDefaultDateNgayTra(JDateChooser dateChooser) {
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.DATE, 10);
        dateChooser.setDate(calendar.getTime());
    }
    private void mochitiet(String MaPhieuMuon,PhieuMuonDTO pm){
        CTPhieuMuonGUI ctpm = null;
        try {
            ctpm = new CTPhieuMuonGUI();
            if(MaPhieuMuon!=null){
                ctpm.setMaPhieuMuon(MaPhieuMuon);
                ctpm.setPm(pm);
                ctpm.updatect();}
        } catch (Exception ex) {
            Logger.getLogger(PhieuMuonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

            
        // Hiển thị JFrame chi tiết phiếu
        ctpm.setVisible(true);
        ctpm.setDefaultCloseOperation(ctpm.HIDE_ON_CLOSE);
    }
    private void mochitiet(){
        mochitiet(null,null);
    }
    private void mochitiet(String maPhieuMuon){
        mochitiet(maPhieuMuon,null);
    }

}
