/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.tacgiaBUS;
import DAO.tacGiaDAO;
import DTO.tacGiaDTO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author DO THE TUNG
 */
public class tacgiaFrame extends javax.swing.JFrame {
DefaultTableModel tableModel = new DefaultTableModel();
    ArrayList<tacGiaDTO> tgList = new ArrayList<>();
    
    /**
     * Creates new form tacgiaFrame
     */
    public tacgiaFrame() {
        initComponents();
        tableModel= (DefaultTableModel) tbltacgia.getModel();
        showdata();
        
    }
    public void showdata()
    {
     
           tacGiaDAO dataDAO = new tacGiaDAO();
        tgList = dataDAO.ReadData();
        
        System.out.println(tgList.toString());
        tableModel.setRowCount(0);
        tgList.forEach((tg)
                -> {
//            System.out.println(nxb.toString());
            tableModel.addRow(new Object[]{tg.getMa(), tg.getTen(),
                tg.getHo(), tg.getGioiTinh(),tg.getSoDienThoai()});
        }
        );

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        txtho = new javax.swing.JTextField();
        txtgioitinh = new javax.swing.JTextField();
        txtsodienthoai = new javax.swing.JTextField();
        btnsua = new javax.swing.JButton();
        xoabtn = new javax.swing.JButton();
        refreshbtn = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnfind = new javax.swing.JButton();
        txtfind = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltacgia = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 104, -1, -1));

        jLabel2.setText("Tên");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 159, -1, -1));

        jLabel3.setText("Họ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 212, -1, -1));

        jLabel4.setText("Gioi Tinh");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 266, -1, -1));

        jLabel5.setText("Số Điện Thoại");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 324, -1, -1));
        getContentPane().add(txtma, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 98, 200, -1));
        getContentPane().add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 153, 200, -1));
        getContentPane().add(txtho, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 206, 200, -1));
        getContentPane().add(txtgioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 260, 200, -1));

        txtsodienthoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsodienthoaiActionPerformed(evt);
            }
        });
        getContentPane().add(txtsodienthoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 318, 200, -1));

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit.png"))); // NOI18N
        btnsua.setText("SỬA");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 446, -1, -1));

        xoabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        xoabtn.setText("XÓA");
        xoabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoabtnActionPerformed(evt);
            }
        });
        getContentPane().add(xoabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 446, -1, -1));

        refreshbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Refresh.png"))); // NOI18N
        refreshbtn.setText("REFRESH");
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });
        getContentPane().add(refreshbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 446, -1, -1));

        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add.png"))); // NOI18N
        btnthem.setText("THÊM");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        getContentPane().add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 446, -1, -1));

        btnfind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search.png"))); // NOI18N
        btnfind.setText("Tìm Kiếm");
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });
        getContentPane().add(btnfind, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 589, -1, -1));

        txtfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfindActionPerformed(evt);
            }
        });
        getContentPane().add(txtfind, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 594, 194, 25));

        jLabel6.setText("Tìm Kiếm");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 599, -1, -1));

        tbltacgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Ho", "Giới Tính", "Số Điện Thoại"
            }
        ));
        tbltacgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltacgiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbltacgia);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 208, 777, 447));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("Quản Lý Tác GIả");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 88, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtsodienthoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsodienthoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsodienthoaiActionPerformed

    private void txtfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfindActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        
        
        
        tacGiaDTO tg =  new tacGiaDTO();

       tg.Ma = Integer.parseInt(txtma.getText());
        tg.Ten = txtten.getText();
        tg.Ho = txtho.getText();
        tg.GioiTinh = txtgioitinh.getText();
        tg.soDienThoai = Integer.parseInt(txtsodienthoai.getText());
        
        tacgiaBUS bus = new tacgiaBUS();
        Vector header = new Vector();
        header.add("Ma");
        header.add("Ten");
        header.add("Ho");
        header.add("GioiTinh");
        header.add("SO Dien Thoai");
        if (tableModel.getRowCount() == 0) {
            tableModel = new DefaultTableModel(header, 0);

        }
        Vector row = new Vector();

        row.add(tg.Ma);
        row.add(tg.Ten);
        row.add(tg.Ho);
        row.add(tg.GioiTinh);
        
        row.add(tg.soDienThoai);

        if (bus.checkMaTacGia(tg.getMa(),tg.getSoDienThoai())) {
            JOptionPane.showMessageDialog(null, "Mã nha xuat ban bi trung hoac so dien thoai bị trung");
        } else {
            tableModel.addRow(row);
            tbltacgia.setModel(tableModel);
            tgList.add(tg);
            bus.insert_BUS(tg);
            JOptionPane.showMessageDialog(null, "THEM tac gia THANH CONG");
            System.out.println(tgList.toString());
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void xoabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoabtnActionPerformed
        // TODO add your handling code here:
        tacgiaBUS bus = new tacgiaBUS();
        int i =tbltacgia.getSelectedRow();
        if (i >= 0) {
            int Ma = Integer.parseInt(txtma.getText());

            tgList.remove(bus.findWithId(Ma));

            bus.xoa(Ma);

            tableModel.removeRow(i);

            tbltacgia.setModel(tableModel);

            System.out.println(tgList.toString());
            JOptionPane.showMessageDialog(null, " DA XOA THANH CONG");

        }
    }//GEN-LAST:event_xoabtnActionPerformed

    private void tbltacgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltacgiaMouseClicked
        // TODO add your handling code here:
          DefaultTableModel clickTable = (DefaultTableModel) tbltacgia.getModel();
        int i = tbltacgia.getSelectedRow();
        try {
            txtma.setText(clickTable.getValueAt(i, 0).toString());
            txtten.setText(clickTable.getValueAt(i, 1).toString());
//            txtmanxb.setText(clickTable.getValueAt(i, 1).toString());

            txtho.setText(clickTable.getValueAt(i, 2).toString());
            txtgioitinh.setText(clickTable.getValueAt(i, 3).toString());
txtsodienthoai.setText(clickTable.getValueAt(i, 4).toString());
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        
    }//GEN-LAST:event_tbltacgiaMouseClicked

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        int i = tbltacgia.getSelectedRow();
        tacgiaBUS bus = new tacgiaBUS();
        if (i >= 0) {
            tacGiaDTO tg = new tacGiaDTO();

            tg.Ma = Integer.parseInt(txtma.getText());
            tg.Ten = txtten.getText();
            tg.Ho = txtho.getText();
            tg.GioiTinh= txtgioitinh.getText();
            tg.soDienThoai = Integer.parseInt(txtsodienthoai.getText());
            tableModel.setValueAt(tg.Ma, i, 0);
            tableModel.setValueAt(tg.Ten, i, 1);
            
            tableModel.setValueAt(tg.Ho, i, 2);
            tableModel.setValueAt(tg.GioiTinh, i, 3);
            tableModel.setValueAt(tg.soDienThoai, i, 4);
            tbltacgia.setModel(tableModel);

            bus.sua(tg);
            JOptionPane.showMessageDialog(null, " DA SUA THANH CONG");

        }
        
    }//GEN-LAST:event_btnsuaActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        // TODO add your handling code here:
         tacGiaDAO dataDAO = new tacGiaDAO();
        tgList = dataDAO.ReadData();
        DefaultTableModel tableModel2 =(DefaultTableModel) tbltacgia.getModel();
        System.out.println(tgList.toString());
        tableModel2.setRowCount(0);
        tgList.forEach((tg)
                -> {
            System.out.println(tg.toString());
            tableModel2.addRow(new Object[]{tg.getMa(), tg.getTen(),
                tg.getHo(), tg.getGioiTinh(),tg.getSoDienThoai()});
        }
        );
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        // TODO add your handling code here:
        
        tacgiaBUS busfind = new tacgiaBUS();
ArrayList <tacGiaDTO> ds = busfind.TimMaTacGia(Integer.parseInt(txtfind.getText()));
//busfind.returnTable(ds);
System.out.println(ds.toString());
tbltacgia.setModel(busfind.returnTable(ds));
    }//GEN-LAST:event_btnfindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tacgiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tacgiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tacgiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tacgiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tacgiaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfind;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JTable tbltacgia;
    private javax.swing.JTextField txtfind;
    private javax.swing.JTextField txtgioitinh;
    private javax.swing.JTextField txtho;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtsodienthoai;
    private javax.swing.JTextField txtten;
    private javax.swing.JButton xoabtn;
    // End of variables declaration//GEN-END:variables
}
